version: '2'
services:
  app:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/api/healthcheck/rancher" "HTTP/1.0"
      reinitializing_timeout: 60000
  mailtrap:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  pma:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
  pra:
    scale: 1
    start_on_create: true

  larakup-lb:
    scale: 1
    start_on_create: true

    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: nginx
        source_port: 7777
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

  tools-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: pma
        source_port: 8082
        target_port: 80
      - priority: 2
        protocol: http
        service: pra
        source_port: 8083
        target_port: 80
      - priority: 3
        protocol: http
        service: mailtrap
        source_port: 8086
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
